name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Cài đặt công cụ kết nối
        shell: powershell
        run: |
          net user runneradmin YourPassword123!
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          ./ngrok/ngrok.exe authtoken 3FczWk7BOcECgv2dXZDACBH1fdT_5g1WAgJ7GEkraoprSoif2

      - name: Kích hoạt RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Khởi chạy Ngrok
        shell: powershell
        run: |
          Start-Process ./ngrok/ngrok.exe -ArgumentList 'tcp 3389'

      - name: Lấy thông tin kết nối
        shell: powershell
        run: |
          $retryCount = 0
          $maxRetries = 20
          $url = ""
          Write-Host "Đang đợi Ngrok khởi động..."
          while ($retryCount -lt $maxRetries -and -not $url) {
              try {
                  $url = (Invoke-RestMethod http://localhost:4040/api/tunnels).tunnels[0].public_url
              } catch {
                  Start-Sleep -Seconds 3
                  $retryCount++
              }
          }
          if ($url) {
              Write-Host "Kết nối qua: mstsc"
              Write-Host "Địa chỉ: $url"
              Write-Host "User: runneradmin"
              Write-Host "Pass: YourPassword123!"
          } else {
              Write-Error "Không thể kết nối tới Ngrok!"
              exit 1
          }

      - name: Giữ máy chạy
        shell: powershell
        run: Start-Sleep -Seconds 21600